export const TYPES = {
  Application: Symbol('Application'),
  CollaborationTrackerService: Symbol('CollaborationTrackerService'),
  SearchService: Symbol('SearchService'),
  ChatSocketService: Symbol('ChatSocketService'),
  DrawingSocketService: Symbol('DrawingSocketService'),
  UploadService: Symbol('UploadService'),
  StatusService: Symbol('StatusService'),
  DbClient: Symbol('DbClient'),
  UserRepository: Symbol('UserRepository'),
  TextChannelRepository: Symbol('TextChannelRepository'),
  TeamRepository: Symbol('TeamRepository'),
  DrawingRepository: Symbol('DrawingRepository'),
  PostRepository: Symbol('PostRepository'),
  MessageRepository: Symbol('MessageRepository'),
  AvatarRepository: Symbol('AvatarRepository'),
};
